version: '3'

services:
  xxl-job-admin-postgres:
    image: xxl-job-admin-postgres:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: zombie-xxl-job-admin
    ports:
      - "8080:8080"
    environment:
      - db_url=jdbc:postgresql://localhost:5432/xxl_job?currentSchema=xxl_job
      - db_username=xxl_job
      - db_password=123456
    network_mode: host
#    depends_on: Published ports are discarded when using host network mode
#      - db

#  db:
#    image: postgres:16.2
#    container_name: zombie_postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - E:/postgres/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=xxl_job
#      - POSTGRES_USER=123456